<?php

/**
 * @file
 * The rothamsted dashboard module.
 */

declare(strict_types=1);

/**
 * Implements hook_farm_dashboard_groups().
 */
function farm_rothamsted_dashboard_farm_dashboard_groups() {
  return [
    'top' => [
      'rothamsted_user_studies' => [
        '#type' => 'details',
        '#open' => FALSE,
        '#title' => t('My Studies'),
        '#weight' => 105,
        '#attributes' => [
          'class' => ['dashboard-pane'],
        ],
      ],
      'rothamsted_user_proposals' => [
        '#type' => 'details',
        '#open' => FALSE,
        '#title' => t('My Proposals'),
        '#weight' => 110,
        '#attributes' => [
          'class' => ['dashboard-pane'],
        ],
      ],
    ],
  ];
}

/**
 * Implements hook_farm_dashboard_panes().
 */
function farm_rothamsted_dashboard_farm_dashboard_panes() {
  return [
    'rothamsted_search' => [
      'block' => 'rothamsted_search',
      'title' => t('Search'),
      'region' => 'top',
      'weight' => 100,
    ],
    'rothamsted_user_proposals' => [
      'block' => 'rothamsted_user_proposals',
      'region' => 'top',
      'group' => 'rothamsted_user_proposals',
    ],
    'rothamsted_user_studies' => [
      'block' => 'rothamsted_user_studies',
      'region' => 'top',
      'group' => 'rothamsted_user_studies',
    ],
  ];
}

/**
 * Implements hook_farm_dashboard_panes_alter().
 */
function farm_rothamsted_dashboard_farm_dashboard_panes_alter(&$panes) {
  $allowed_panes = [
    'rothamsted_search',
    'rothamsted_user_proposals',
    'rothamsted_user_studies',
    'dashboard_map',
  ];
  foreach (array_keys($panes) as $pane) {
    if (!in_array($pane, $allowed_panes)) {
      unset($panes[$pane]);
    }
  }
}
