<?php

/**
 * @file
 * The rothamsted dashboard module.
 */

/**
 * Implements hook_farm_dashboard_groups().
 */
function farm_rothamsted_dashboard_farm_dashboard_groups() {
  return [
    'top' => [
      'rothamsted_user_studies' => [
        '#type' => 'details',
        '#open' => FALSE,
        '#title' => t('My Studies'),
        '#weight' => 105,
      ],
      'rothamsted_user_proposals' => [
        '#type' => 'details',
        '#open' => FALSE,
        '#title' => t('My Proposals'),
        '#weight' => 110,
      ],
    ],
  ];
}

/**
 * Implements hook_farm_dashboard_panes().
 */
function farm_rothamsted_dashboard_farm_dashboard_panes() {
  return [
    'rothamsted_search' => [
      'block' => 'rothamsted_search',
      'title' => t('Search'),
      'region' => 'top',
      'weight' => 100,
    ],
    'rothamsted_user_proposals' => [
      'block' => 'rothamsted_user_proposals',
      'region' => 'top',
      'group' => 'rothamsted_user_proposals',
    ],
    'rothamsted_user_studies' => [
      'block' => 'rothamsted_user_studies',
      'region' => 'top',
      'group' => 'rothamsted_user_studies',
    ],
  ];
}
