<?php

/**
 * @file
 * The rothamsted export module.
 */

declare(strict_types=1);

use Drupal\farm_rothamsted_export\Form\ExportDataActionForm;
use Drupal\farm_rothamsted_export\Routing\ExportDataActionRouteProvider;

/**
 * Implements hook_entity_type_build().
 */
function farm_rothamsted_export_entity_type_build(array &$entity_types) {

  // Enable the entity export data action on target entity types.
  $target_entity_types = [
    'asset',
    'log',
    'quantity',
    'plan',
    'rothamsted_researcher',
    'rothamsted_design',
    'rothamsted_experiment',
    'rothamsted_program',
    'rothamsted_proposal',
  ];
  foreach ($target_entity_types as $entity_type) {
    if (!empty($entity_types[$entity_type])) {
      $route_providers = $entity_types[$entity_type]->getRouteProviderClasses();
      $route_providers['export-data'] = ExportDataActionRouteProvider::class;
      $entity_types[$entity_type]->setHandlerClass('route_provider', $route_providers);
      $entity_types[$entity_type]->setLinkTemplate('export-data-action-form', "/$entity_type/export");
      $entity_types[$entity_type]->setFormClass('export-data-action-form', ExportDataActionForm::class);
    }
  }
}
