<?php

/**
 * @file
 * Contains farm_rothamsted.module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Defines the cossh hazard assessments options.
 *
 * @return array
 *   The cossh hazard options.
 */
function farm_rothamsted_cossh_hazard_options() {
  return [
    'explosive' => new TranslatableMarkup('Explosive'),
    'oxidising' => new TranslatableMarkup('Oxidising'),
    'flammable' => new TranslatableMarkup('Flammable'),
    'highly_flammable' => new TranslatableMarkup('Highly Flammable'),
    'extremely_flammable' => new TranslatableMarkup('Extremely Flammable'),
    'harmful' => new TranslatableMarkup('Harmful'),
    'irritant' => new TranslatableMarkup('Irritant'),
    'corrosive' => new TranslatableMarkup('Corrosive'),
    'toxic' => new TranslatableMarkup('Toxic'),
    'danger_to_environment' => new TranslatableMarkup('Danger to Environment'),
    'carcinogenic' => new TranslatableMarkup('Carcinogenic'),
    'mutagenic' => new TranslatableMarkup('Mutagenic'),
    'toxic_for_reproduction' => new TranslatableMarkup('Toxic for Reproduction'),
    'sensitising' => new TranslatableMarkup('Sensitising'),
    'none' => new TranslatableMarkup('None'),
  ];
}

/**
 * Defines the ppe options.
 *
 * @return array
 *   The ppe options.
 */
function farm_rothamsted_ppe_options() {
  return [
    'face_shield' => new TranslatableMarkup('Face Shield'),
    'coveralls' => new TranslatableMarkup('Coveralls'),
    'gloves' => new TranslatableMarkup('Gloves'),
    'apron' => new TranslatableMarkup('Apron'),
  ];
}

/**
 * Allowed values callback function for the ppe field.
 *
 * @param \Drupal\Core\Field\FieldStorageDefinitionInterface $definition
 *   The field storage definition.
 * @param \Drupal\Core\Entity\ContentEntityInterface|null $entity
 *   The entity being created if applicable.
 * @param bool $cacheable
 *   Boolean indicating if the allowed values can be cached. Defaults to TRUE.
 *
 * @return array
 *   Returns an array of allowed values for use in form select options.
 */
function farm_rothamsted_ppe_field_allowed_values(FieldStorageDefinitionInterface $definition, ?ContentEntityInterface $entity = NULL, bool &$cacheable = TRUE) {
  return farm_rothamsted_ppe_options();
}

/**
 * Allowed values callback function for the cossh hazards field.
 *
 * @param \Drupal\Core\Field\FieldStorageDefinitionInterface $definition
 *   The field storage definition.
 * @param \Drupal\Core\Entity\ContentEntityInterface|null $entity
 *   The entity being created if applicable.
 * @param bool $cacheable
 *   Boolean indicating if the allowed values can be cached. Defaults to TRUE.
 *
 * @return array
 *   Returns an array of allowed values for use in form select options.
 */
function farm_rothamsted_cossh_hazard_field_allowed_values(FieldStorageDefinitionInterface $definition, ?ContentEntityInterface $entity = NULL, bool &$cacheable = TRUE) {
  return farm_rothamsted_cossh_hazard_options();
}

/**
 * Implements hook_removed_post_updates().
 */
function farm_rothamsted_removed_post_updates() {
  return [
    'farm_rothamsted_post_update_add_harvest_storage_location_field' => '3.x',
    'farm_rothamsted_post_update_create_drain_structure_type2' => '3.x',
    'farm_rothamsted_post_update_create_rothamsted_asset_parent_action' => '3.x',
    'farm_rothamsted_post_update_create_rothamsted_uncategorized_logs_view' => '3.x',
    'farm_rothamsted_post_update_create_seed_dressing_field' => '3.x',
    'farm_rothamsted_post_update_remove_rothamsted_asset_parent_action' => '3.x',
    'farm_rothamsted_post_update_2_10_1_create_rothamsted_date_format' => '3.x',
    'farm_rothamsted_post_update_2_10_2_enable_experiment_research' => '3.x',
    'farm_rothamsted_post_update_2_17_enable_role_submodule' => '3.x',
    'farm_rothamsted_post_update_2_26_map_snapshot' => '3.x',
  ];
}
