<?php

declare(strict_types=1);

/**
 * @file
 * Contains farm_rothamsted_roles.module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_entity_extra_field_info().
 */
function farm_rothamsted_roles_entity_extra_field_info() {
  $fields['user']['user']['display']['rothamsted_user_roles'] = [
    'label' => t('User roles'),
    'description' => t('The user\'s roles and permissions.'),
    'weight' => 0,
  ];
  return $fields;
}

/**
 * Implements hook_ENTITY_TYPE_view() for user entities.
 */
function farm_rothamsted_roles_user_view(array &$build, UserInterface $account, EntityViewDisplayInterface $display) {

  $current_user = \Drupal::currentUser();
  $access = $account->id() === $current_user->id() || $current_user->hasPermission('administer users');
  if ($access && $display->getComponent('rothamsted_user_roles')) {
    $role_labels = array_map(function ($role) {
      return $role->label();
    }, $account->get('roles')->referencedEntities());
    $build['rothamsted_user_roles'] = [
      '#type' => 'item',
      '#markup' => '<h4 class="label">' . t('User roles') . '</h4> ' . implode(', ', $role_labels),
    ];
  }
}
