<?php

/**
 * @file
 * The farm rothamsted comment module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_entity_insert().
 */
function farm_rothamsted_comment_entity_insert(EntityInterface $entity) {
  if ($entity->getEntityTypeId() != 'comment') {
    return;
  }

  // Only send emails for comments about these entity types.
  $core_entity_type_ids = [
    'asset',
    'log',
    'plan',
  ];
  if (!in_array($entity->bundle(), $core_entity_type_ids)) {
    return;
  }

  // Add entity type logic.
  $emails = [];

  // Include commented entity owners.
  /** @var \Drupal\comment\CommentInterface $comment */
  $comment = $entity;
  if (($commented = $comment->getCommentedEntity()) && $commented->hasField('owner')) {
    $emails = array_map(function (UserInterface $user) {
      return $user->getEmail();
    }, $commented->get('owner')->referencedEntities());
  }

  // Send comment update to authors of parent comments.
  $parent_count = 0;
  /** @var \Drupal\comment\Entity\Comment $comment */
  $comment = $entity;
  while ($comment->hasParentComment() && $parent_count < 5) {
    $parent_count++;
    $comment = $comment->getParentComment();
    if ($email = $comment->getAuthorEmail()) {
      $emails[] = $email;
    }
  }

  // Bail if there is no one to send email.
  if (empty($emails)) {
    return;
  }

  // Get the entity and add a token variable for the entity type.
  $entity_type_id = $entity->getEntityTypeId();
  $params[$entity_type_id] = $entity;

  // Build email string.
  $emails = array_unique(array_filter($emails));
  $email_string = implode(', ', $emails);

  // Send mail.
  /** @var \Drupal\Core\Mail\MailManagerInterface $mail_manager */
  $mail_manager = \Drupal::service('plugin.manager.mail');
  $mail_manager->mail('farm_rothamsted_notification', 'comment', $email_string, 'en', $params);
}
