<?php

/**
 * @file
 * The farm rothamsted comment module.
 */

use Drupal\Core\Entity\EntityFormInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\log\Entity\LogInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_form_alter().
 */
function farm_rothamsted_comment_form_alter(array &$form, FormStateInterface &$form_state, string $form_id) {

  // Bail if not the right form.
  $form_object = $form_state->getFormObject();
  if ($form_id != 'comment_log_form' || !$form_object instanceof EntityFormInterface) {
    return;
  }

  // Default value.
  $existing_flags = array_column($form_object->getEntity()->getCommentedEntity()?->get('flag')?->getValue() ?? [], 'value');
  $default = in_array('review', $existing_flags);

  // Add checkbox to flag log for review.
  $form['log_flag_review'] = [
    '#type' => 'checkbox',
    '#title' => t('Flag that the Log "Needs Review"'),
    '#default_value' => $default,
  ];
  $form['actions']['submit']['#submit'][] = 'farm_rothamsted_comment_form_log_flag_submit';
}

/**
 * Submit callback for comment log flag form field.
 */
function farm_rothamsted_comment_form_log_flag_submit(array $form, FormStateInterface $form_state) {

  // Check that the log_flag_review field is set.
  if (!$form_state->hasValue('log_flag_review')) {
    return;
  }

  // Check if the box was checked to flag the log for review.
  $review_flag = $form_state->getValue('log_flag_review');

  // Check that we have a commented log.
  /** @var \Drupal\comment\CommentInterface $comment */
  $comment = $form_state->getFormObject()->getEntity();
  $log = $comment->getCommentedEntity();
  if (($log instanceof LogInterface) && $log->hasField('flag')) {

    // Add review to log flags.
    $flag_field = $log->get('flag');
    $existing_flags = array_column($flag_field->getValue(), 'value');
    $flag_field->setValue([]);

    // Append or remove the review flag.
    if ($review_flag) {
      $new_flags = array_unique(array_merge($existing_flags, ['review']));
      $message = '@user flagged log for review.';
    }
    else {
      $new_flags = array_diff($existing_flags, ['review']);
      $message = '@user unflagged log for review.';
    }
    foreach ($new_flags as $flag) {
      $flag_field->appendItem($flag);
    }

    // Return if there are no changes to the flag field.
    if ($new_flags === $existing_flags) {
      return;
    }

    // Set a revision and save the log.
    $log->setNewRevision(TRUE);
    $log->setRevisionUser($comment->getOwner());
    // phpcs:ignore
    $log->setRevisionLogMessage(t($message, ['@user' => $comment->getOwner()->getDisplayName()]));
    $log->save();
  }
}

/**
 * Implements hook_entity_insert().
 */
function farm_rothamsted_comment_entity_insert(EntityInterface $entity) {
  if ($entity->getEntityTypeId() != 'comment') {
    return;
  }

  // Only send emails for comments about these entity types.
  $core_entity_type_ids = [
    'asset',
    'log',
    'plan',
  ];
  if (!in_array($entity->bundle(), $core_entity_type_ids)) {
    return;
  }

  // Add entity type logic.
  $emails = [];

  // Include commented entity owners.
  /** @var \Drupal\comment\CommentInterface $comment */
  $comment = $entity;
  if (($commented = $comment->getCommentedEntity()) && $commented->hasField('owner')) {
    $emails = array_map(function (UserInterface $user) {
      return $user->getEmail();
    }, $commented->get('owner')->referencedEntities());
  }

  // Send comment update to authors of parent comments.
  $parent_count = 0;
  /** @var \Drupal\comment\Entity\Comment $comment */
  $comment = $entity;
  while ($comment->hasParentComment() && $parent_count < 5) {
    $parent_count++;
    $comment = $comment->getParentComment();
    if ($email = $comment->getAuthorEmail()) {
      $emails[] = $email;
    }
  }

  // Do not send updates to the current user.
  if ($current_user_email = \Drupal::currentUser()->getEmail()) {
    $emails = array_diff($emails, [$current_user_email]);
  }
  $emails = array_unique(array_filter($emails));

  // Bail if there is no one to send email.
  if (empty($emails)) {
    return;
  }

  // Get the entity and add a token variable for the entity type.
  $entity_type_id = $entity->getEntityTypeId();
  $params['entity_type_id'] = $entity_type_id;
  $params[$entity_type_id] = $entity;

  // Build email string.
  $emails = array_unique(array_filter($emails));
  $email_string = implode(', ', $emails);

  // Send mail.
  /** @var \Drupal\Core\Mail\MailManagerInterface $mail_manager */
  $mail_manager = \Drupal::service('plugin.manager.mail');
  $mail_manager->mail('farm_rothamsted_notification', 'comment', $email_string, 'en', $params);
}
