# Schema for plot_column_descriptor field formatter.
field.formatter.settings.plot_column_descriptor:
  type: mapping
  mapping:
    column_id:
      type: string
      label: 'Column id'
    column_levels:
      type: string
      label: 'Column levels'
    raw:
      type: boolean
      label: 'Raw values'
    value_only:
      type: boolean
      label: 'Value only'
# Schema for views filter plugins.
views.filter.column_level:
  type: views.filter.in_operator
  label: 'Column level filter'
views.filter.plan_plot_type:
  type: views.filter.many_to_one
  label: 'Plan plot type filter'

# Schema for plan status actions.
action.configuration.plan_active_action:
  type: action_configuration_default
  label: 'Configuration for the plan status active'
action.configuration.plan_cancelled_action:
  type: action_configuration_default
  label: 'Configuration for the plan status cancelled'
action.configuration.plan_completed_action:
  type: action_configuration_default
  label: 'Configuration for the plan status completed'
action.configuration.plan_planning_action:
  type: action_configuration_default
  label: 'Configuration for the plan status planning'
action.configuration.plan_requested_action:
  type: action_configuration_default
  label: 'Configuration for the plan status requested'
