<?php

/**
 * @file
 * Contains farm_rothamsted_researcher.module.
 */

declare(strict_types=1);

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Access\AccessResultAllowed;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function farm_rothamsted_researcher_rothamsted_researcher_access(EntityInterface $entity, $operation, AccountInterface $account) {

  // Only check view and update operations.
  if (!in_array($operation, ['update', 'view']) || $entity->get('farm_user')->isEmpty()) {
    return AccessResult::neutral();
  }

  // Only check if the farm_user is the current user.
  if ($entity->farm_user->entity->id() == $account->id()) {
    // Allow access if the user has the view/update own permission.
    return AccessResultAllowed::allowedIf($account->hasPermission("$operation assigned rothamsted_researcher"));
  }

  // Else return neutral.
  return AccessResult::neutral();
}

/**
 * Implements hook_removed_post_updates().
 */
function farm_rothamsted_researcher_removed_post_updates() {
  return [
    'farm_rothamsted_researcher_post_update_2_12_create_researcher_reference_view' => '3.x',
    'farm_rothamsted_researcher_post_update_2_14_remove_orcid_prefix' => '3.x',
    'farm_rothamsted_researcher_post_update_2_16_notification_field' => '3.x',
    'farm_rothamsted_researcher_post_update_2_18_remove_email_notification_fields' => '3.x',
    'farm_rothamsted_researcher_post_update_2_21_comments' => '3.x',
    'farm_rothamsted_researcher_post_update_2_28_multiple_roles' => '3.x',
  ];
}
