<?php

/**
 * @file
 * Contains farm_rothamsted_researcher.module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Access\AccessResultAllowed;
use Drupal\Core\Entity\Display\EntityFormDisplayInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Url;
use Drupal\farm_rothamsted_researcher\Entity\RothamstedResearcherInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme_registry_alter().
 */
function farm_rothamsted_researcher_theme_registry_alter(&$theme_registry) {

  // Register preprocess function to add link to user toolbar.
  if (isset($theme_registry['links__toolbar_user']['preprocess functions'])) {
    $theme_registry['links__toolbar_user']['preprocess functions'][] = 'farm_rothamsted_researcher_preprocess_links__toolbar_user';
  }
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function farm_rothamsted_researcher_rothamsted_researcher_access(EntityInterface $entity, $operation, AccountInterface $account) {

  // Only check view and update operations.
  if (!in_array($operation, ['update', 'view']) || $entity->get('farm_user')->isEmpty()) {
    return AccessResult::neutral();
  }

  // Only check if the farm_user is the current user.
  if ($entity->farm_user->entity->id() == $account->id()) {
    // Allow access if the user has the view/update own permission.
    return AccessResultAllowed::allowedIf($account->hasPermission("$operation assigned rothamsted_researcher"));
  }

  // Else return neutral.
  return AccessResult::neutral();
}

/**
 * Implements hook_entity_form_display_alter().
 */
function farm_rothamsted_researcher_entity_form_display_alter(EntityFormDisplayInterface $form_display, array $context) {
  $comment_bundles = [
    'rothamsted_researcher',
  ];
  if ($form_display->getTargetEntityTypeId() == 'comment' && in_array($context['bundle'], $comment_bundles) && $form_display->getMode() == 'default' && $form_display->isNew()) {
    $form_display->setComponent('author', [
      'region' => 'content',
      'settings' => [],
      'weight' => 0,
    ]);
    $form_display->setComponent('comment_body', [
      'type' => 'text_textarea',
      'region' => 'content',
      'settings' => [
        'rows' => 5,
        'placeholder' => '',
      ],
      'weight' => 1,
    ]);
    $form_display->removeComponent('subject');
  }
}

/**
 * Implements hook_entity_view_display_alter().
 */
function farm_rothamsted_researcher_entity_view_display_alter(EntityViewDisplayInterface $display, array $context) {
  $comment_bundles = [
    'rothamsted_researcher',
  ];
  $display_modes = ['default', 'full'];
  if ($context['entity_type'] == 'comment' && in_array($context['bundle'], $comment_bundles) && in_array($display->getMode(), $display_modes) && $display->isNew()) {
    $display->setComponent('comment_body', [
      'type' => 'text_default',
      'label' => 'hidden',
      'region' => 'content',
      'settings' => [],
      'weight' => 0,
    ]);
    $display->setComponent('links', [
      'region' => 'content',
      'settings' => [],
      'weight' => 1,
    ]);
  }
}

/**
 * Preprocess function to add links to the user toolbar.
 */
function farm_rothamsted_researcher_preprocess_links__toolbar_user(&$variables) {
  $links = [
    'researcher_profile' => [
      'link' => [
        '#type' => 'link',
        '#title' => t('View Researcher profile'),
        '#url' => Url::fromRoute('farm_rothamsted_researcher.current_user_researcher'),
      ],
      '#weight' => -10,
    ],
  ];
  $variables['links'] = $links + $variables['links'];
}

/**
 * Implements hook_entity_extra_field_info().
 */
function farm_rothamsted_researcher_entity_extra_field_info() {
  $fields['user']['user']['display']['researcher_profile'] = [
    'label' => t('Researcher profile roles'),
    'description' => t("The user's researcher profile."),
    'weight' => -5,
  ];
  $fields['rothamsted_researcher']['rothamsted_researcher']['display']['user_profile'] = [
    'label' => t('User profile'),
    'description' => t('The researcher user profile.'),
    'weight' => 0,
  ];
  return $fields;
}

/**
 * Implements hook_ENTITY_TYPE_view() for user entities.
 */
function farm_rothamsted_researcher_user_view(array &$build, UserInterface $account, EntityViewDisplayInterface $display) {

  // Query for the current user's researcher profile.
  if ($display->getComponent('researcher_profile')) {
    $researchers = Drupal::entityTypeManager()->getStorage('rothamsted_researcher')->loadByProperties([
      'farm_user' => $account->id(),
    ]);
    /** @var \Drupal\farm_rothamsted_researcher\Entity\RothamstedResearcherInterface $researcher */
    if ($researcher = reset($researchers)) {
      $build['researcher_profile'] = [
        '#type' => 'item',
        '#markup' => '<h4 class="label">' . t('Researcher profile') . '</h4> ' . $researcher->toLink($researcher->label())->toString(),
      ];
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_view() for rothamsted_researcher entities.
 */
function farm_rothamsted_researcher_rothamsted_researcher_view(array &$build, RothamstedResearcherInterface $researcher, EntityViewDisplayInterface $display) {
  if ($display->getComponent('user_profile')) {

    // Bail if researcher doesn't have a farm user.
    if ($researcher->get('farm_user')->isEmpty()) {
      return;
    }

    // Get referenced user.
    $users = $researcher->get('farm_user')->referencedEntities();
    $user = reset($users);

    // Include user roles if user has access.
    $current_user = \Drupal::currentUser();
    $role_labels = NULL;
    if ($user->id() === $current_user->id() || $current_user->hasPermission('administer users')) {
      $role_labels = implode(
        ', ',
        array_map(function ($role) {
          return $role->label();
        }, $user->get('roles')->referencedEntities())
      );
      $role_labels = " ($role_labels)";
    }

    // Build text.
    $build['researcher_profile'] = [
      '#type' => 'item',
      '#markup' => '<h4 class="label">' . t('farmOS User profile') . '</h4> ' . $user->toLink($user->label())->toString() . $role_labels,
    ];
  }
}

/**
 * Implements hook_local_tasks_alter().
 */
function farm_rothamsted_researcher_local_tasks_alter(&$local_tasks) {
  // Disable Drupal core revisions local tasks.
  unset($local_tasks['entity.version_history:rothamsted_researcher.version_history']);
}

/**
 * Implements hook_theme().
 */
function farm_rothamsted_researcher_theme() {
  return [
    'rothamsted_researcher' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function farm_rothamsted_researcher_theme_suggestions_rothamsted_researcher(array $variables) {
  $suggestions = [];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');
  $suggestions[] = 'rothamsted_researcher__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function farm_rothamsted_researcher_preprocess_rothamsted_researcher__full(&$variables) {
  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  $variables['#attached']['library'][] = 'farm_ui_theme/layout';
  farm_ui_theme_build_stacked_twocol_layout($variables, 'rothamsted_researcher');
}
