<?php

/**
 * @file
 * Contains farm_rothamsted_notification.module.
 */

declare(strict_types=1);

/**
 * Helper function to compare two entity object arrays.
 *
 * Modified from the core DiffArray::diffAssocRecursive() to work for
 * edge cases in field comparisons.
 *
 * @param array $array1
 *   The array to compare from.
 * @param array $array2
 *   The array to compare to.
 *
 * @return array
 *   Returns array field keys that are different.
 *
 * @see DiffArray::diffAssocRecursive()
 */
function farm_rothamsted_notification_compare_entity_fields(array $array1, array $array2) {
  $difference = [];
  foreach ($array1 as $key => $value) {
    if (is_array($value)) {
      // Type comparison.
      if (!array_key_exists($key, $array2) || !is_array($array2[$key])) {
        $difference[] = $key;
      }
      // Field length differences.
      elseif (count($value) !== count($array2[$key])) {
        // Check that a value actually exists when comparing compound fields.
        // This fixes a bug where notes always appears to be changing when
        // there is no value.
        if (count($value) === 0 && isset($array2[$key][0]['value']) && is_null($array2[$key][0]['value'])) {
          continue;
        }
        $difference[] = $key;
      }
      // Recursive difference.
      else {
        $new_diff = farm_rothamsted_notification_compare_entity_fields($value, $array2[$key]);
        if (!empty($new_diff)) {
          $difference[] = $key;
        }
      }
    }
    // Do not use an exact comparison so int can compare to string.
    elseif (!array_key_exists($key, $array2) || $array2[$key] != $value) {
      $difference[] = $key;
    }
  }
  return $difference;
}
