<?php

declare(strict_types=1);

/**
 * @file
 * Contains farm_rothamsted_notification.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Url;

/**
 * Implements hook_entity_base_field_info().
 */
function farm_rothamsted_notification_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];
  if ($entity_type->id() == 'user') {
    $fields['rothamsted_notification_email'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Email notifications'))
      ->setDescription(t('Switch off all e-mail notifications. Please note that there are some e-mail notifications which cannot be switched off for authentic purposes. For example if someone creates a Research Profile on your behalf, or if someone names you on a Research Program, Proposal, Experiment or Design.'))
      ->setDefaultValue(TRUE)
      ->setRevisionable(TRUE)
      ->setRequired(TRUE)
      ->setSettings([
        'on_label' => t('Enabled'),
        'off_label' => t('Disabled'),
      ])
      ->setDisplayConfigurable('form', FALSE)
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('view', [
        'type' => 'boolean',
        'label' => 'inline',
      ]);

    $fields['rothamsted_notification_researcher'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Researcher updates'))
      ->setDescription(t('Switch on/off e-mail notifications relating to changes to your Researcher profile in FarmOS. If this is switched off, you will no longer receive notifications if someone other than you edits your Researcher profile (e.g. an administrator). This is on by default. If you leave it on, you will receive e-mails as soon as any changes are made.'))
      ->setDefaultValue(TRUE)
      ->setRevisionable(TRUE)
      ->setSettings([
        'on_label' => t('Enabled'),
        'off_label' => t('Disabled'),
      ])
      ->setDisplayConfigurable('form', FALSE)
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('view', [
        'type' => 'boolean',
        'label' => 'inline',
      ]);

    $fields['rothamsted_notification_program'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Research Program updates'))
      ->setDescription(t('Switch on/off e-mail notifications relating to changes to a or any Research Programs you are associated with in FarmOS. If this is switched off, you will no longer receive notifications if someone other than you edits a Research Program where you are named as a PI (e.g. an administrator). This is on by default. If you leave it on, you will receive e-mails as soon as any changes are made.'))
      ->setDefaultValue(TRUE)
      ->setRevisionable(TRUE)
      ->setSettings([
        'on_label' => t('Enabled'),
        'off_label' => t('Disabled'),
      ])
      ->setDisplayConfigurable('form', FALSE)
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('view', [
        'type' => 'boolean',
        'label' => 'inline',
      ]);

    $fields['rothamsted_notification_proposal'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Proposal updates'))
      ->setDescription(t('Switch on/off e-mail notifications relating to changes to a or any Proposals you are associated with in FarmOS. If this is switched off, you will no longer receive notifications if someone other than you edits a Proposal you are named on. This is on by default. If you leave it on, you will receive e-mails as soon as any changes are made.'))
      ->setDefaultValue(TRUE)
      ->setRevisionable(TRUE)
      ->setSettings([
        'on_label' => t('Enabled'),
        'off_label' => t('Disabled'),
      ])
      ->setDisplayConfigurable('form', FALSE)
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('view', [
        'type' => 'boolean',
        'label' => 'inline',
      ]);

    $fields['rothamsted_notification_experiment'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Experiment updates'))
      ->setDescription(t('Switch on/off e-mail notifications relating to changes to a or any Experiment, Design or Plan you are associated with in FarmOS. If this is switched off, you will no longer receive notifications if someone other than you edits an Experiment, Design or Plan you are associated with. This is on by default. If you leave it on, you will receive e-mails as soon as any changes are made.'))
      ->setDefaultValue(TRUE)
      ->setRevisionable(TRUE)
      ->setSettings([
        'on_label' => t('Enabled'),
        'off_label' => t('Disabled'),
      ])
      ->setDisplayConfigurable('form', FALSE)
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('view', [
        'type' => 'boolean',
        'label' => 'inline',
      ]);

    $fields['rothamsted_notification_log'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Log notifications'))
      ->setDescription(t('Switch on/off e-mail notifications for logs. If this is switched of you will no longer receive notifications when someone (e.g. farm staff) adds or edits the logs associated with the experiments you are named on. This is on by default. If you leave it on, you will receive e-mails as soon as new logs are added or any changes are made.'))
      ->setDefaultValue(TRUE)
      ->setRevisionable(TRUE)
      ->setRequired(TRUE)
      ->setSettings([
        'on_label' => t('Enabled'),
        'off_label' => t('Disabled'),
      ])
      ->setDisplayConfigurable('form', FALSE)
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('view', [
        'type' => 'boolean',
        'label' => 'inline',
      ]);
  }
  return $fields;
}

/**
 * Helper function to compare two entity object arrays.
 *
 * Modified from the core DiffArray::diffAssocRecursive() to work for
 * edge cases in field comparisons.
 *
 * @param array $array1
 *   The array to compare from.
 * @param array $array2
 *   The array to compare to.
 *
 * @return array
 *   Returns array field keys that are different.
 *
 * @see DiffArray::diffAssocRecursive()
 */
function farm_rothamsted_notification_compare_entity_fields(array $array1, array $array2) {
  $difference = [];
  foreach ($array1 as $key => $value) {
    if (is_array($value)) {
      // Type comparison.
      if (!array_key_exists($key, $array2) || !is_array($array2[$key])) {
        $difference[] = $key;
      }
      // Field length differences.
      elseif (count($value) !== count($array2[$key])) {
        // Check that a value actually exists when comparing compound fields.
        // This fixes a bug where notes always appears to be changing when
        // there is no value.
        if (count($value) === 0 && isset($array2[$key][0]['value']) && is_null($array2[$key][0]['value'])) {
          continue;
        }
        $difference[] = $key;
      }
      // Recursive difference.
      else {
        $new_diff = farm_rothamsted_notification_compare_entity_fields($value, $array2[$key]);
        if (!empty($new_diff)) {
          $difference[] = $key;
        }
      }
    }
    // Do not use an exact comparison so int can compare to string.
    elseif (!array_key_exists($key, $array2) || $array2[$key] != $value) {
      $difference[] = $key;
    }
  }
  return $difference;
}
